In [ ]:
import pandas as pd

df=pd.read_csv("ecommerce_user_behavior_8000.csv")

In [ ]:
df.head()

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
0,1.0,56.0,Female,Desktop,12.90,8.0,13.0,1.0,1.0,NaN,0.0,6.97,28.18,1.0
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17,86.73,1.0
2,3.0,32.0,Female,NaN,11.64,12.0,11.0,0.0,0.0,0.0,1.0,8.87,83.09,1.0
3,4.0,25.0,Female,Mobile,22.71,5.0,10.0,1.0,0.0,0.0,1.0,NaN,79.03,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15,55.35,1.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             7840 non-null   float64
 1   age                 7840 non-null   float64
 2   gender              7840 non-null   object
 3   device_type         7840 non-null   object
 4   time_on_site        7840 non-null   float64
 5   pages_viewed        7840 non-null   float64
 6   previous_purchases  7840 non-null   float64
 7   cart_items          7840 non-null   float64
 8   discount_seen       7840 non-null   float64
 9   ad_clicked          7840 non-null   float64
 10  returning_user      7840 non-null   float64
 11  avg_session_time    7840 non-null   float64
 12  bounce_rate         7840 non-null   float64
 13  purchase            7840 non-null   float64
dtypes: float64(12), object(2)
memory usage: 875.1+ KB

In [ ]:
df.describe(include="all")

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
count,7840.000000,7840.000000,7840,7840,7840.000000,7840.000000,7840.000000,7840.000000,7840.000000,7840.000000,7840.000000,7840.000000,7840.000000,7840.000000
unique,NaN,NaN,2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,Male,Mobile,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,3931,4685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,4003.135077,38.595791,NaN,NaN,15.714673,9.970026,6.964158,4.530230,0.502551,0.502296,0.509439,15.794999,49.924402,0.998342
std,2307.898984,12.033928,NaN,NaN,8.362764,5.425485,4.281117,2.865814,0.500025,0.500027,0.499943,9.864556,29.137449,0.040689
min,1.000000,18.000000,NaN,NaN,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.570000,0.010000,0.000000
25%,2011.750000,28.000000,NaN,NaN,8.520000,5.000000,3.000000,2.000000,0.000000,0.000000,0.000000,7.750000,24.677500,1.000000
50%,3998.000000,39.000000,NaN,NaN,15.740000,10.000000,7.000000,5.000000,1.000000,1.000000,1.000000,14.300000,49.500000,1.000000
75%,6001.250000,49.000000,NaN,NaN,22.880000,15.000000,11.000000,7.000000,1.000000,1.000000,1.000000,22.392500,75.990000,1.000000
max,8000.000000,59.000000,NaN,NaN,30.000000,19.000000,14.000000,9.000000,1.000000,1.000000,1.000000,44.750000,99.970000,1.000000

In [ ]:
df.isnull().sum()

user_id               160
age                   160
gender                160
device_type           160
time_on_site          160
pages_viewed          160
previous_purchases    160
cart_items            160
discount_seen         160
ad_clicked            160
returning_user        160
avg_session_time      160
bounce_rate           160
purchase              160
dtype: int64

In [ ]:
df.count()

user_id               7840
age                   7840
gender                7840
device_type           7840
time_on_site          7840
pages_viewed          7840
previous_purchases    7840
cart_items            7840
discount_seen         7840
ad_clicked            7840
returning_user        7840
avg_session_time      7840
bounce_rate           7840
purchase              7840
dtype: int64

In [ ]:
df.shape

(8000, 14)

In [ ]:
df.isnull().sum(axis=1)

1       0
4       0
5       0
6       0
7       0
       ..
7995    0
7996    0
7997    0
7998    0
7999    0
Length: 6019, dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.head(10)

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17,86.73,1.0
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15,55.35,1.0
5,6.0,56.0,Female,Desktop,26.60,1.0,12.0,7.0,1.0,1.0,0.0,28.40,13.90,1.0
6,7.0,36.0,Male,Mobile,7.60,11.0,11.0,6.0,1.0,1.0,1.0,4.51,13.12,1.0
7,8.0,40.0,Female,Mobile,26.98,7.0,5.0,2.0,1.0,0.0,0.0,33.34,12.61,1.0
8,9.0,28.0,Female,Mobile,10.90,14.0,7.0,9.0,0.0,0.0,1.0,13.80,85.46,1.0
9,10.0,28.0,Female,Mobile,9.97,3.0,14.0,8.0,0.0,0.0,0.0,14.12,14.16,1.0
10,11.0,41.0,Female,Tablet,22.08,11.0,14.0,4.0,1.0,1.0,0.0,23.43,80.85,1.0
11,12.0,53.0,Female,Mobile,9.84,17.0,6.0,2.0,1.0,0.0,0.0,5.97,84.47,1.0
12,13.0,57.0,Male,Desktop,2.54,18.0,6.0,6.0,0.0,0.0,1.0,3.37,10.50,1.0

In [ ]:
df['engagement']=df['time_on_site']*df['pages_viewed']

In [ ]:
df

,user_id,age,gender,device_type,time_on_site,pages_viewed,previous_purchases,cart_items,discount_seen,ad_clicked,returning_user,avg_session_time,bounce_rate,purchase,engagement
1,2.0,46.0,Male,Mobile,15.63,9.0,4.0,6.0,1.0,1.0,1.0,19.17,86.73,1.0,140.67
4,5.0,38.0,Female,Mobile,26.35,9.0,12.0,4.0,1.0,0.0,0.0,18.15,55.35,1.0,237.15
5,6.0,56.0,Female,Desktop,26.60,1.0,12.0,7.0,1.0,1.0,0.0,28.40,13.90,1.0,26.60
6,7.0,36.0,Male,Mobile,7.60,11.0,11.0,6.0,1.0,1.0,1.0,4.51,13.12,1.0,83.60
7,8.0,40.0,Female,Mobile,26.98,7.0,5.0,2.0,1.0,0.0,0.0,33.34,12.61,1.0,188.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,7996.0,48.0,Female,Tablet,2.67,10.0,6.0,0.0,1.0,0.0,1.0,3.01,82.44,1.0,26.70
7996,7997.0,54.0,Male,Mobile,18.94,13.0,11.0,4.0,1.0,1.0,1.0,27.48,10.06,1.0,246.22
7997,7998.0,54.0,Female,Desktop,24.08,8.0,13.0,1.0,0.0,0.0,1.0,27.57,21.34,1.0,192.64
7998,7999.0,32.0,Female,Mobile,10.85,13.0,12.0,8.0,1.0,1.0,0.0,5.78,2.03,1.0,141.05
7999,8000.0,46.0,Female,Mobile,12.23,2.0,9.0,2.0,0.0,1.0,1.0,8.28,15.67,1.0,24.46

In [ ]:
df['avg_time_per_page']=df['time_on_site']/df['pages_viewed']

In [ ]:
df['avg_time_per_page']

1        1.736667
4        2.927778
5       26.600000
6        0.690909
7        3.854286
          ...
7995     0.267000
7996     1.456923
7997     3.010000
7998     0.834615
7999     6.115000
Name: avg_time_per_page, Length: 6019, dtype: float64

In [ ]:
import numpy as np

df['returning_customer']=np.where(df['previous_purchases']>0,"Yes","No")

In [ ]:
df[['previous_purchases','returning_customer']].head(10)

    previous_purchases returning_customer
1                  4.0                Yes
4                 12.0                Yes
5                 12.0                Yes
6                 11.0                Yes
7                  5.0                Yes
8                  7.0                Yes
9                 14.0                Yes
10                14.0                Yes
11                 6.0                Yes
12                 6.0                Yes

In [ ]:
df['age_group']=np.where(df['age']<25,'Young',
                         np.where(df['age']<40,'Adult',
                         np.where(df['age']<60,'Middle-aged',
                         'Senior')))

In [ ]:
df[['age','age_group']].head(20)

     age    age_group
1   46.0  Middle-aged
4   38.0        Adult
5   56.0  Middle-aged
6   36.0        Adult
7   40.0  Middle-aged
8   28.0        Adult
9   28.0        Adult
10  41.0  Middle-aged
11  53.0  Middle-aged
12  57.0  Middle-aged
13  41.0  Middle-aged
14  20.0        Young
15  39.0        Adult
17  41.0  Middle-aged
18  47.0  Middle-aged
19  55.0  Middle-aged
21  38.0        Adult
22  50.0  Middle-aged
23  29.0        Adult
24  39.0        Adult

In [ ]:
df.to_csv("cleaned_ecommerce_data.csv",index=False)

In [ ]:
import os
os.getcwd()

'/content'

In [ ]:
from google.colab import files
files.download("cleaned_ecommerce_data.csv")